version: '3.8'  # Keep the version declaration if using Docker Compose version 1.27.0+

services:
  back-end:
    build:
      context: ./node
      dockerfile: Dockerfile
    command:
      - npm
      - run
      - start
    container_name: back-end
    depends_on:
      - db  # Simply list the service name
    networks:
      - node-network
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app

  db:
    container_name: postgres_container
    environment:
      POSTGRES_DB: postgres_container
      POSTGRES_PASSWORD: "1234"
      POSTGRES_USER: postgres
    image: postgres:13
    networks:
      - node-network
    ports:
      - "5432:5432"
    restart: always
    tty: true
    volumes:
      - pgdata:/var/lib/postgresql/data

  front-end:
    build:
      context: ./react
      dockerfile: Dockerfile
    command:
      - npm
      - run
      - dev
    container_name: front-end
    depends_on:
      - back-end  # Simply list the service name
    networks:
      - node-network
    ports:
      - "5173:5173"
    tty: true
    volumes:
      - ./react:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    depends_on:
      - back-end  # Simply list the service name
      - front-end  # Simply list the service name
    networks:
      - node-network
    ports:
      - "8000:80"
    restart: always
    tty: true

networks:
  node-network:
    driver: bridge

volumes:
  pgdata:  # Named volume for PostgreSQL data storage
