version: '3.8'

services:
  back-end:
    build: 
      context: ./node
    container_name: back-end
    working_dir: /usr/src/app
    networks: 
      - node-network
    volumes: 
      - ./node:/usr/src/app
    tty: true
    ports: 
      - "3000:3000"
    command: npm run start
    depends_on:
      - db

  front-end:
    build: 
      context: ./react
    container_name: front-end
    working_dir: /usr/src/app
    networks: 
      - node-network
    volumes: 
      - ./react:/usr/src/app
    tty: true
    ports: 
      - "5173:5173"
    command: npm run dev

  db:
    image: postgres:13
    container_name: postgres_container
    restart: always
    tty: true
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres_container
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
    networks: 
      - node-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    build: 
      context: ./nginx
    container_name: nginx
    restart: always
    tty: true
    ports: 
      - "8000:80"
    networks: 
      - node-network
    depends_on:
      - back-end
      - front-end
  
networks: 
  node-network:
    driver: bridge

volumes:
  pgdata: 
