name: CI for Dockerized App

# Trigger the workflow on pushes to the main branch
on:
  push:
    branches: [ development  ]

jobs:
  build-and-test:
    # Use the latest Ubuntu runner
    runs-on: ubuntu-latest

    steps:
      # Checkout code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker Buildx (required for advanced Docker builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build Docker images using docker-compose
      - name: Build Docker images
        run: docker-compose -f docker-compose.yml build

      # Run the services in the background using Docker Compose
      - name: Run services using Docker Compose
        run: docker-compose up -d

      # (Optional) Run your backend tests (for Node.js backend)
      - name: Run backend tests
        run: docker-compose run backend npm test

      # (Optional) Run frontend tests (for React)
      - name: Run frontend tests
        run: docker-compose run frontend npm test

      # Tear down the Docker services after tests
      - name: Tear down Docker services
        run: docker-compose down
