name: CI/CD for Dockerized App

on:
  push:
    branches: [development]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and run services
        run: docker-compose -f docker-compose.yml up --build -d

      - name: Wait for PostgreSQL
        run: |
          until docker-compose exec -T db pg_isready -U ${DB_USER}; do
            echo "Waiting for Postgres to be ready..."
            sleep 5
          done

      - name: Run backend tests
        run: docker-compose run back-end npm test

      - name: Run frontend tests
        run: docker-compose run front-end npm test

      - name: Tear down Docker services
        run: docker-compose down

      - name: Remove Docker volumes
        run: docker-compose down --volumes

      - name: Send Notification Email
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        run: |
          curl --request POST \
          --url https://api.sendgrid.com/v3/mail/send \
          --header 'Authorization: Bearer '${SENDGRID_API_KEY} \
          --header 'Content-Type: application/json' \
          --data '{
            "personalizations": [
              {
                "to": [
                  {
                    "email": "andualemasamenew5@gmail.com"
                  }
                ],
                "subject": "CI/CD Pipeline Notification"
              }
            ],
            "from": {
              "email": ""email": "andualemasamenew5@gmail.com"  # Replace with your SendGrid verified sender email
            },
            "content": [
              {
                "type": "text/plain",
                "value": "Your CI/CD pipeline has completed successfully!"
              }
            ]
          }'
